# Generated by Django 5.2 on 2025-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('support', 'Support'), ('superuser', 'Superuser'), ('teacher', 'Teacher')], default='student'),
        ),
    ]
