# Generated by Django 5.2 on 2025-04-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bootcamp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'کنسل شده')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_bootcamp', to='bootcamp.bootcamp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'bootcamp')},
            },
        ),
    ]
