# Generated by Django 5.2 on 2025-05-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_bootcamp_ticket_ticket_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_file',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_image',
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='ticket_images')),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='ticket_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='ticket.ticket')),
            ],
        ),
    ]
